{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cf389ac",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5002/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [06/Jan/2022 15:20:38] \"\u001b[37mGET /getjson/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:20:51] \"\u001b[37mGET /getexectime/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:20:51] \"\u001b[37mGET /getjson/ HTTP/1.1\u001b[0m\" 200 -\n",
      "[2022-01-06 15:20:51,905] ERROR in app: Exception on /getMaxmem/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 239, in get_Maxmem_penode\n",
      "    data= json.load(file)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "127.0.0.1 - - [06/Jan/2022 15:20:51] \"\u001b[35m\u001b[1mGET /getMaxmem/ HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:20:51] \"\u001b[37mGET /UpdateStatus/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:20:52] \"\u001b[37mGET /getmem/ HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['ID', 'HOSTNAME', 'STATUS', 'AVAILABILITY', 'MANAGER', 'STATUS', 'ENGINE', 'VERSION'], ['1celhfq6kopudt1flvjbhylhd', 'manager', 'Ready', 'Active', 'Leader', '19.03.12'], ['re59vi6ty2j1zdiftxqzw6ffw', 'worker1', 'Ready', 'Active', '19.03.12'], ['zsom7lsidhveg8vimp178kej8', 'worker2', 'Ready', 'Active', '19.03.12']]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/Jan/2022 15:22:25] \"\u001b[37mPOST /getStatus/ HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['worker1', 're59vi6ty2j1zdiftxqzw6ffw', 'worker', '1', '1.033252864', '90.33', '26.73'], ['manager', '1celhfq6kopudt1flvjbhylhd', 'Leader', '1', '1.033252864', '90.87', '32.56'], ['worker2', 'zsom7lsidhveg8vimp178kej8', 'worker', '1', '1.033252864', '90.87', '32.56']]\n",
      "worker1\n",
      "worker\n",
      "manager\n",
      "Leader\n",
      "worker2\n",
      "worker\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/Jan/2022 15:22:26] \"\u001b[37mGET /getjson/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:14] \"\u001b[37mGET /getjson/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:19] \"\u001b[37mGET /getexectime/ HTTP/1.1\u001b[0m\" 200 -\n",
      "[2022-01-06 15:23:19,278] ERROR in app: Exception on /getcpu/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 188, in get_cpu_per_container\n",
      "    data= json.load(file)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8195 (char 8194)\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:19] \"\u001b[35m\u001b[1mGET /getcpu/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:23:19,278] ERROR in app: Exception on /getmem/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 214, in get_mem_per_container\n",
      "    data= json.load(file)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8195 (char 8194)\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:19] \"\u001b[35m\u001b[1mGET /getmem/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:23:19,397] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8195 (char 8194)\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:19] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:19] \"\u001b[37mGET /UpdateStatus/ HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['ID', 'HOSTNAME', 'STATUS', 'AVAILABILITY', 'MANAGER', 'STATUS', 'ENGINE', 'VERSION'], ['1celhfq6kopudt1flvjbhylhd', 'manager', 'Ready', 'Active', 'Leader', '19.03.12'], ['re59vi6ty2j1zdiftxqzw6ffw', 'worker1', 'Ready', 'Active', '19.03.12'], ['zsom7lsidhveg8vimp178kej8', 'worker2', 'Ready', 'Active', '19.03.12']]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2022-01-06 15:23:23,555] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 8195 (char 8194)\n",
      "127.0.0.1 - - [06/Jan/2022 15:23:23] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:36] \"\u001b[37mGET /getexectime/ HTTP/1.1\u001b[0m\" 200 -\n",
      "[2022-01-06 15:25:37,005] ERROR in app: Exception on /getmem/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 214, in get_mem_per_container\n",
      "    data= json.load(file)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:37] \"\u001b[35m\u001b[1mGET /getmem/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:25:37,095] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:37] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:37] \"\u001b[37mGET /UpdateStatus/ HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['ID', 'HOSTNAME', 'STATUS', 'AVAILABILITY', 'MANAGER', 'STATUS', 'ENGINE', 'VERSION'], ['1celhfq6kopudt1flvjbhylhd', 'manager', 'Ready', 'Active', 'Leader', '19.03.12'], ['re59vi6ty2j1zdiftxqzw6ffw', 'worker1', 'Ready', 'Active', '19.03.12'], ['zsom7lsidhveg8vimp178kej8', 'worker2', 'Ready', 'Active', '19.03.12']]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/Jan/2022 15:25:37] \"\u001b[37mGET /getcpu/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:40] \"\u001b[37mGET /getjson/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:46] \"\u001b[37mGET /getexectime/ HTTP/1.1\u001b[0m\" 200 -\n",
      "[2022-01-06 15:25:46,678] ERROR in app: Exception on /getmem/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 214, in get_mem_per_container\n",
      "    data= json.load(file)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:46] \"\u001b[35m\u001b[1mGET /getmem/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:25:46,679] ERROR in app: Exception on /getcpu/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 188, in get_cpu_per_container\n",
      "    data= json.load(file)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:46] \"\u001b[35m\u001b[1mGET /getcpu/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:25:46,775] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:46] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:46] \"\u001b[37mGET /UpdateStatus/ HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['ID', 'HOSTNAME', 'STATUS', 'AVAILABILITY', 'MANAGER', 'STATUS', 'ENGINE', 'VERSION'], ['1celhfq6kopudt1flvjbhylhd', 'manager', 'Ready', 'Active', 'Leader', '19.03.12'], ['re59vi6ty2j1zdiftxqzw6ffw', 'worker1', 'Ready', 'Active', '19.03.12'], ['zsom7lsidhveg8vimp178kej8', 'worker2', 'Ready', 'Active', '19.03.12']]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2022-01-06 15:25:53,372] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:25:53] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:26:33,574] ERROR in app: Exception on /getmem/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 204, in get_mem_per_container\n",
      "    Instance=createInstance(instance)\n",
      "  File \"/Users/anwar/Workspace/ford project/Untitled/many-objective-container-scheduling/source-code/scheduling-container-in-python/Constrained Approach/Problem/Instance_from_Json.py\", line 20, in createInstance\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:26:33] \"\u001b[37mGET /getexectime/ HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:26:33] \"\u001b[35m\u001b[1mGET /getmem/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:26:33,575] ERROR in app: Exception on /getcpu/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 178, in get_cpu_per_container\n",
      "    Instance=createInstance(instance)\n",
      "  File \"/Users/anwar/Workspace/ford project/Untitled/many-objective-container-scheduling/source-code/scheduling-container-in-python/Constrained Approach/Problem/Instance_from_Json.py\", line 20, in createInstance\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:26:33] \"\u001b[35m\u001b[1mGET /getcpu/ HTTP/1.1\u001b[0m\" 500 -\n",
      "[2022-01-06 15:26:33,682] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [06/Jan/2022 15:26:33] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [06/Jan/2022 15:26:33] \"\u001b[37mGET /UpdateStatus/ HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['ID', 'HOSTNAME', 'STATUS', 'AVAILABILITY', 'MANAGER', 'STATUS', 'ENGINE', 'VERSION'], ['1celhfq6kopudt1flvjbhylhd', 'manager', 'Ready', 'Active', 'Leader', '19.03.12'], ['re59vi6ty2j1zdiftxqzw6ffw', 'worker1', 'Ready', 'Active', '19.03.12'], ['zsom7lsidhveg8vimp178kej8', 'worker2', 'Ready', 'Active', '19.03.12']]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2022-01-06 15:26:34,312] ERROR in app: Exception on /getjson/ [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask_restful/__init__.py\", line 271, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-2e05b8155233>\", line 33, in getjson\n",
      "    data = json.load(f)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/__init__.py\", line 357, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/anwar/opt/anaconda3/lib/python3.8/json/decoder.py\", line 353, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 8215 (char 8214)\n",
      "127.0.0.1 - - [06/Jan/2022 15:26:34] \"\u001b[35m\u001b[1mGET /getjson/ HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python3\n",
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "Created on Thu Apr  8 09:50:11 2021\n",
    "\n",
    "@author: anwar\n",
    "\"\"\"\n",
    "\n",
    "from flask import request\n",
    "from flask import Flask, jsonify\n",
    "import json\n",
    "import requests\n",
    "import subprocess\n",
    "from launchAlgo import transform\n",
    "from flask_restful import Api\n",
    "from flask_cors import CORS\n",
    "app = Flask(__name__)\n",
    "api = Api(app)\n",
    "cors = CORS(app, resources={r\"/*\": {\"origins\": \"*\"}})\n",
    "from instance.Instance import Instance\n",
    "from Problem.Instance_from_Json import createInstance\n",
    "import extract_data\n",
    "\n",
    "\n",
    "\n",
    "instance=Instance()\n",
    "url='http://192.168.99.110:9090/'\n",
    "\n",
    "@app.route('/getjson/', methods=['GET'])\n",
    "def getjson():\n",
    "    f = open(r\"instanceExamples/data.json\")\n",
    "\n",
    "    data = json.load(f)\n",
    "    response = app.response_class(\n",
    "        response=json.dumps(data),\n",
    "        mimetype='application/json'\n",
    "    )\n",
    "    return response\n",
    "\n",
    "@app.route('/getenergy/', methods=['GET'])\n",
    "def getcsv():\n",
    "    f = open(r\"./energy.json\")\n",
    "\n",
    "    data = json.load(f)\n",
    "    response = app.response_class(\n",
    "        response=json.dumps(data),\n",
    "        mimetype='application/json'\n",
    "    )\n",
    "    return response\n",
    "\n",
    "\n",
    "@app.route('/update/', methods=['POST'])\n",
    "def events():\n",
    "\n",
    "\n",
    "    content = request.get_data()\n",
    "    c=json.loads(content)\n",
    "    #print(c)\n",
    "    with open(r\"instanceExamples/data.json\", 'w') as f:\n",
    "        json.dump(c, f)\n",
    "    return 'JSON posted'\n",
    "\n",
    "\n",
    "@app.route('/getStatus/', methods=['POST'])\n",
    "def getStatus():\n",
    "\n",
    "\n",
    "    content = request.get_data()\n",
    "    c=json.loads(content)\n",
    "    print(c)\n",
    "    update(c)\n",
    "    return json.dumps(c)\n",
    "    \n",
    "    # with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "\n",
    "    #     data= json.load(file)\n",
    "    #     data['objectives']=c\n",
    "\n",
    "    # with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "    #     json.dump(data, file)\n",
    "    # return json.dumps(c)\n",
    "    \n",
    "    \n",
    "   \n",
    "def update(result):\n",
    "    with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "        data= json.load(file)\n",
    "    for row in result:\n",
    "        for node in data['nodes']:\n",
    "            if(node['name']==row[0]):\n",
    "                print(node['name'])\n",
    "                print(row[2])\n",
    "                node['Manager Status']=row[2]\n",
    "                if(row[2]=='Reachable'):\n",
    "                    \n",
    "                    cmd = ('docker-machine ssh manager docker node promote '+str(node['name'])).split()\n",
    "                    print(cmd)\n",
    "                    p = subprocess.Popen(cmd)\n",
    "                    output, errors = p.communicate()\n",
    "                    \n",
    "    with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "        json.dump(data, file)\n",
    "        \n",
    "    \n",
    "\n",
    "@app.route('/getweights/', methods=['POST'])\n",
    "def weights():\n",
    "\n",
    "\n",
    "    content = request.get_data()\n",
    "    c=json.loads(content)\n",
    "    #print(c)\n",
    "    with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "\n",
    "        data= json.load(file)\n",
    "        data['objectives']=c\n",
    "\n",
    "    with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "        json.dump(data, file)\n",
    "    return json.dumps(c)\n",
    "\n",
    "@app.route('/UpdateStatus/', methods=['GET'])\n",
    "def get_nodes():\n",
    "\n",
    "        machines=[]\n",
    "\n",
    "        with  open(r\"./test3.txt\",'w') as file :\n",
    "\n",
    "\n",
    "            cmd = ('docker-machine ssh manager docker node ls').split()\n",
    "\n",
    "            p = subprocess.Popen(cmd,stdout=file)\n",
    "            output, errors = p.communicate()\n",
    "            \n",
    "        info=[]\n",
    "\n",
    "        with open(r\"./test3.txt\",'r') as file:\n",
    "\n",
    "            \n",
    "            for line in file:\n",
    "                \n",
    "                line=line.replace(\"*\",'')\n",
    "                groupe=line.split()\n",
    "                info.append(groupe)\n",
    "                \n",
    "                machines.append(groupe[1])\n",
    "\n",
    "            del machines[0]\n",
    "            print(info)\n",
    "            if (info[1][4]=='Unreachable'):\n",
    "               \n",
    "                msg=\"Leader is down, another manager has been selected!\"\n",
    "               \n",
    "                return(jsonify(msg))\n",
    "            else:\n",
    "                #print(groupe)\n",
    "                msg=\"done\"\n",
    "                #print(msg)\n",
    "                return(jsonify(msg))\n",
    "\n",
    "\n",
    "\n",
    "@app.route('/default/', methods=['GET'])\n",
    "def get():\n",
    "    cmd = ('ssh root@manager docker stack deploy --compose-file initial-docker-compose.yml p').split()\n",
    "\n",
    "    p = subprocess.Popen(cmd,stdout = subprocess.PIPE)\n",
    "    output, errors = p.communicate()\n",
    "\n",
    "    print(output)\n",
    "    print(errors)\n",
    "    result=jsonify(\"done\")\n",
    "\n",
    "    return (result)\n",
    "\n",
    "# @app.route('/getcpu/', methods=['GET'])\n",
    "# def get_cpu_per_container():\n",
    "#     Instance=createInstance(instance)\n",
    "#     for node in Instance.nodes:\n",
    "\n",
    "#         r = requests.get(url+'api/v1/query?query=sum(irate(container_cpu_usage_seconds_total%7Bcontainer_label_com_docker_swarm_node_id%3D~\"'+str(node.cluster_id[0])+'\"%2C%20id%3D~\"%2Fdocker%2F.*\"%7D%5B5m%5D))%20by%20(name)%20*%20100%20&g0.tab=1')\n",
    "\n",
    "#         for metric in json.loads(r.text)['data']['result']:\n",
    "\n",
    "#             name=(metric['metric']['name'])\n",
    "\n",
    "#             with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "#                 data= json.load(file)\n",
    "#             for con in data['containers']:\n",
    "#                 if (con['name'] in name):\n",
    "\n",
    "#                     con['cpu_usage']=float(metric['value'][1])\n",
    "\n",
    "#             with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "\n",
    "#                 json.dump(data, file)\n",
    "\n",
    "\n",
    "\n",
    "#     return (jsonify('done'))\n",
    "\n",
    "@app.route('/getmem/', methods=['GET'])\n",
    "def get_mem_per_container():\n",
    "    Instance=createInstance(instance)\n",
    "    for node in Instance.nodes:\n",
    "\n",
    "        r = requests.get(url+'api/v1/query?query=avg_over_time(container_memory_usage_bytes%7Bcontainer_label_com_docker_swarm_node_id%3D~\"'+str(node.cluster_id[0])+'\"%2C%20id%3D~\"%2Fdocker%2F.*\"%7D%5B5m%5D)%2F1024%2F1024&g0.tab=1')\n",
    "\n",
    "\n",
    "        for metric in json.loads(r.text)['data']['result']:\n",
    "\n",
    "            name=(metric['metric']['name'])\n",
    "            with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "                data= json.load(file)\n",
    "            for con in data['containers']:\n",
    "                if (con['name'] in name):\n",
    "\n",
    "                    con['mem_usage']=float(metric['value'][1])\n",
    "\n",
    "            with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "\n",
    "                json.dump(data, file)\n",
    "\n",
    "    for node in Instance.nodes:\n",
    "        #print(node.cluster_id)\n",
    "        r = requests.get(url+'api/v1/query?query=sum(node_memory_MemTotal_bytes%20*%20on(instance)%20group_left(node_name)%20node_meta%7Bnode_id%3D~\"'+str(node.cluster_id[0])+'\"%7D)%2F1000%2F1000&g0.tab=1')\n",
    "\n",
    "        #print(json.loads(r.text)['data']['result'][0]['value'][1])\n",
    "\n",
    "        with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "            data= json.load(file)\n",
    "        for con in data['nodes']:\n",
    "\n",
    "            if (con['name'] == node.name):\n",
    "\n",
    "\n",
    "                con['Maxmem']=float(json.loads(r.text)['data']['result'][0]['value'][1])\n",
    "\n",
    "        with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "\n",
    "            json.dump(data, file)\n",
    "            \n",
    "    for node in Instance.nodes:\n",
    "\n",
    "        r = requests.get(url+'api/v1/query?query=sum(irate(container_cpu_usage_seconds_total%7Bcontainer_label_com_docker_swarm_node_id%3D~\"'+str(node.cluster_id[0])+'\"%2C%20id%3D~\"%2Fdocker%2F.*\"%7D%5B5m%5D))%20by%20(name)%20*%20100%20&g0.tab=1')\n",
    "\n",
    "        for metric in json.loads(r.text)['data']['result']:\n",
    "\n",
    "            name=(metric['metric']['name'])\n",
    "\n",
    "            with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "                data= json.load(file)\n",
    "            for con in data['containers']:\n",
    "                if (con['name'] in name):\n",
    "\n",
    "                    con['cpu_usage']=float(metric['value'][1])\n",
    "\n",
    "            with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "\n",
    "                json.dump(data, file)\n",
    "\n",
    "    return (jsonify('done'))\n",
    "\n",
    "\n",
    "# @app.route('/getMaxmem/', methods=['GET'])\n",
    "# def get_Maxmem_penode():\n",
    "#     Instance=createInstance(instance)\n",
    "#     for node in Instance.nodes:\n",
    "#         #print(node.cluster_id)\n",
    "#         r = requests.get(url+'api/v1/query?query=sum(node_memory_MemTotal_bytes%20*%20on(instance)%20group_left(node_name)%20node_meta%7Bnode_id%3D~\"'+str(node.cluster_id[0])+'\"%7D)%2F1000%2F1000&g0.tab=1')\n",
    "\n",
    "#         #print(json.loads(r.text)['data']['result'][0]['value'][1])\n",
    "\n",
    "#         with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "#             data= json.load(file)\n",
    "#         for con in data['nodes']:\n",
    "\n",
    "#             if (con['name'] == node.name):\n",
    "\n",
    "\n",
    "#                 con['Maxmem']=float(json.loads(r.text)['data']['result'][0]['value'][1])\n",
    "\n",
    "#         with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "\n",
    "#             json.dump(data, file)\n",
    "\n",
    "\n",
    "\n",
    "#     return (jsonify('done'))\n",
    "\n",
    "\n",
    "\n",
    "@app.route('/newapproach/', methods=['GET'])\n",
    "\n",
    "def new_approach():\n",
    "\n",
    "\n",
    "    Instance=createInstance(instance)\n",
    "    time=transform(Instance)\n",
    "    y = {\"containers\":len(Instance.containers),\n",
    "     \"exectime\": round(time, 2)\n",
    "\n",
    "    }\n",
    "    with open(r\"./instanceExamples/exec.json\", \"r\") as file:\n",
    "        data= json.load(file)\n",
    "        data[\"times\"].append(y)\n",
    "\n",
    "\n",
    "    with open(r\"./instanceExamples/exec.json\", \"w\") as file:\n",
    "        json.dump(data, file)\n",
    "\n",
    "    cmd = ('docker-machine ssh manager docker stack deploy --compose-file updated-docker-compose.yml p ').split()\n",
    "\n",
    "    p = subprocess.Popen(cmd)\n",
    "    output, errors = p.communicate()\n",
    "\n",
    "\n",
    "    # print(output)\n",
    "    # print(errors)\n",
    "#        ssh.connect(hostname='ec2-54-87-55-164.compute-1.amazonaws.com', username='ubuntu',pkey=privkey)\n",
    "#        #ssh.connect(\"ubuntu@ec2-54-87-55-164.compute-1.amazonaws.com\",)\n",
    "#        stdin, stdout, stderr=ssh.exec_command('rmdir test')\n",
    "#        print (stdout.read())\n",
    "#        print(stderr.read())\n",
    "\n",
    "\n",
    "\n",
    "    result=jsonify(time)\n",
    "\n",
    "    return (result)\n",
    "@app.route('/getexectime/', methods=['GET'])\n",
    "\n",
    "def gettimes():\n",
    "    f = open(r\"./instanceExamples/exec.json\", \"r\")\n",
    "\n",
    "    data = json.load(f)\n",
    "    response = app.response_class(\n",
    "        response=json.dumps(data),\n",
    "        mimetype='application/json'\n",
    "    )\n",
    "    return response\n",
    "\n",
    "if __name__ == '__main__':\n",
    "     app.run(port='5002')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f246e2d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting flask_restful\n",
      "  Using cached Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB)\n",
      "Requirement already satisfied: Flask>=0.8 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from flask_restful) (1.1.2)\n",
      "Requirement already satisfied: pytz in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from flask_restful) (2021.1)\n",
      "Requirement already satisfied: six>=1.3.0 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from flask_restful) (1.15.0)\n",
      "Collecting aniso8601>=0.82\n",
      "  Using cached aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)\n",
      "Requirement already satisfied: click>=5.1 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from Flask>=0.8->flask_restful) (7.1.2)\n",
      "Requirement already satisfied: Werkzeug>=0.15 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from Flask>=0.8->flask_restful) (1.0.1)\n",
      "Requirement already satisfied: Jinja2>=2.10.1 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from Flask>=0.8->flask_restful) (2.11.3)\n",
      "Requirement already satisfied: itsdangerous>=0.24 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from Flask>=0.8->flask_restful) (1.1.0)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in /Users/anwar/opt/anaconda3/lib/python3.8/site-packages (from Jinja2>=2.10.1->Flask>=0.8->flask_restful) (1.1.1)\n",
      "Installing collected packages: aniso8601, flask-restful\n",
      "Successfully installed aniso8601-9.0.1 flask-restful-0.3.9\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install flask_restful\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81c50c9c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9f9042d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7adcc3d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "Created on Wed Apr 28 14:12:45 2021\n",
    "\n",
    "@author: anwar\n",
    "\"\"\"\n",
    "\n",
    "from datetime import datetime\n",
    "from random import random\n",
    "import json\n",
    "from instance.Instance import Instance\n",
    "from Problem.Instance_from_Json import createInstance\n",
    "\n",
    "# datetime object containing current date and time\n",
    "\n",
    "\n",
    "\n",
    "instance=Instance()\n",
    "Instance=createInstance(instance)\n",
    "\n",
    "\n",
    "\n",
    "import threading\n",
    "\n",
    "    \n",
    "with open(r'./energy.json', mode='w', encoding='utf-8') as file:\n",
    "    entry={}\n",
    "    containers=[]\n",
    "    for con in instance.containers:\n",
    "    \n",
    "        con={'container':con.name,'energy_per_period':[]}\n",
    "        containers.append(con)\n",
    "    entry['containers']=containers\n",
    "    json.dump(entry, file)\n",
    "def generate_energy():\n",
    "    values=[]\n",
    "    date=datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    for i,con in enumerate(instance.containers):\n",
    "        val=int(random()*con.MaxpowerConsumption)\n",
    "        values.append(val)\n",
    "        key={'x':date,'y':val}\n",
    "        \n",
    "        with open(\"./energy.json\", \"r\") as jsonFile:\n",
    "            \n",
    "            data = json.load(jsonFile)\n",
    "            data['containers'][i]['energy_per_period'].append(key)\n",
    "        with open(\"./energy.json\", \"w\") as jsonFile:\n",
    "            json.dump(data, jsonFile)\n",
    "\n",
    "def set_interval(func, sec):\n",
    "    def func_wrapper():\n",
    "        set_interval(func,sec)\n",
    "        func()\n",
    "    t = threading.Timer(sec, func_wrapper)\n",
    "    t.start()\n",
    "    return t\n",
    "\n",
    "def power_average():\n",
    "    with open(r\"./energy.json\", \"r\") as jsonFile:\n",
    "        \n",
    "            \n",
    "            data = json.load(jsonFile)\n",
    "            with open(r\"./instanceExamples/data.json\", \"r\") as file:\n",
    "                all_instance = json.load(file)\n",
    "            for con in data['containers']:\n",
    "                data_for_last_minute=con['energy_per_period'][-6:]\n",
    "                sum=0\n",
    "                average=0\n",
    "                for d in data_for_last_minute:\n",
    "                    sum+=d['y']\n",
    "                average=sum/6\n",
    "                print(average)\n",
    "                for con1 in all_instance['containers']:\n",
    "                    if (con1['name']==con['container']):\n",
    "                            \n",
    "                        con1['average_power_consumption_per_minute']=average\n",
    "                        \n",
    "            with open(r\"./instanceExamples/data.json\", \"w\") as file:\n",
    "                \n",
    "                json.dump(all_instance, file)\n",
    "    \n",
    "\n",
    "set_interval(generate_energy,10)\n",
    "set_interval(power_average,15)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2c809de",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "076b126c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
